import { CONFIG } from './config.js';

const translations = {
  es: {
    brand:'MyCode',
    nav:{courses:'Cursos',plans:'Planes',dashboard:'Dashboard',login:'Iniciar sesión',register:'Registrarse',logout:'Salir',language:'Idioma',back:'← Volver'},
    common:{browse:'Explorar cursos',open:'Abrir',select:'Seleccionar plan',update:'Actualizar plan',current:'Plan actual',cancel:'Cancelar',close:'Cerrar',demo:'Demo frontend: no uses datos reales.',loading:'Cargando…'},
    auth:{registerEyebrow:'CREAR CUENTA',registerTitle:'Empieza en MyCode',registerIntro:'Crea tu cuenta y recibe automáticamente el plan Bronce con 50 tokens.',username:'Nombre de usuario',email:'Correo electrónico',password:'Contraseña',confirmPassword:'Confirmar contraseña',birthDate:'Fecha de nacimiento',userType:'Tipo de usuario',student:'Estudiante',general:'Usuario general',create:'Crear cuenta',already:'¿Ya tienes cuenta?',loginEyebrow:'MYCODE',loginTitle:'Inicia sesión',loginIntro:'Accede a tu dashboard, cursos y tokens.',identifier:'Usuario o correo',submit:'Iniciar sesión',noAccount:'¿No tienes cuenta?',invalidEmail:'Introduce un correo electrónico válido.',required:'Este campo es obligatorio.',usernameMin:'Usa entre 3 y 30 caracteres.',passwordMin:'La contraseña debe tener al menos 8 caracteres e incluir mayúsculas, minúsculas y un número.',passwordMismatch:'Las contraseñas no coinciden.',duplicate:'Este correo ya está registrado.',invalidCredentials:'Usuario o contraseña incorrectos.',unauthorized:'Sesión no autorizada.',forbidden:'No tienes permisos para realizar esta acción.',created:'Cuenta creada correctamente.',loginSuccess:'Sesión iniciada correctamente.',logoutSuccess:'Sesión cerrada.',showPassword:'Mostrar contraseña',hidePassword:'Ocultar contraseña'},
    plans:{eyebrow:'MEMBRESÍAS',heading:'Elige tu nivel',subheading:'Más tokens, más herramientas y acceso premium.',invalidPlan:'Plan no válido',recommended:'RECOMENDADO',advanced:'PARA USUARIOS AVANZADOS',select:'Seleccionar plan',update:'Actualizar plan',changed:'Plan actualizado correctamente.',bronzeDesc:'Para comenzar a aprender y practicar.',silverDesc:'Para quienes quieren más herramientas y margen de uso.',goldDesc:'La experiencia completa de MyCode para usuarios avanzados.',bronzeBenefit1:'50 tokens mensuales',bronzeBenefit2:'Contenido básico',bronzeBenefit3:'Funciones esenciales',silverBenefit1:'120 tokens mensuales',silverBenefit2:'Contenido ampliado',silverBenefit3:'Más funciones de MyCode',silverBenefit4:'Soporte estándar',goldBenefit1:'350 tokens mensuales',goldBenefit2:'Todas las funciones premium',goldBenefit3:'Prioridad en funciones basadas en IA',goldBenefit4:'Herramientas avanzadas de programación',goldBenefit5:'Límites superiores de uso',goldBenefit6:'Acceso anticipado a nuevas funciones',goldBenefit7:'Soporte prioritario y beneficios exclusivos'},
    tokens:{required:'Requeridos',available:'Disponibles',consumed:'Consumo realizado.',lowTitle:'Tus tokens están por agotarse.',lowText:'Considera revisar tu plan.',criticalTitle:'Te quedan pocos tokens.',criticalText:'Algunas funciones podrían dejar de estar disponibles.',emptyTitle:'Has agotado tus tokens disponibles.',emptyText:'Actualiza tu plan para continuar utilizando las funciones premium de MyCode.',viewPlans:'Ver planes',insufficient:'No tienes suficientes tokens para utilizar esta función.'},
    dashboard:{eyebrow:'DASHBOARD',hello:'Hola,',intro:'Controla tu plan, tokens y actividad desde un solo lugar.',wallet:'BILLETERA',tokensTitle:'Tokens disponibles',available:'Disponibles',used:'Utilizados',renewal:'Renovación',days:'días',currentPlan:'Plan actual',history:'Historial de tokens',date:'Fecha',action:'Acción',tokens:'Tokens',emptyHistory:'Aún no hay movimientos.',explore:'Explorar cursos'},
    home:{eyebrow:'APRENDE · CREA · PROGRAMA',title:'Tu código. Tu siguiente nivel.',intro:'Una plataforma de aprendizaje con membresías y tokens consumibles.',catalog:'CATÁLOGO',heading:'Lenguajes para construir',subheading:'El acceso depende de tu plan. Algunas funciones consumen tokens.',memberships:'MEMBRESÍAS',membershipHeading:'Elige el nivel que mejor se adapta a ti',membershipSubheading:'Más tokens, más herramientas y acceso premium.',searchPlaceholder:'Busca cursos o contenido: variables, loops, Python…',searchLabel:'Buscar contenido',noResults:'No encontramos resultados para tu búsqueda.',results:'Resultados'},
    courses:{cppTitle:'C++',cppDescription:'Fundamentos, lógica, estructuras y programación orientada a objetos.',javaTitle:'Java',javaDescription:'Construye aplicaciones robustas con clases, objetos y buenas prácticas.',pythonTitle:'Python',pythonDescription:'Aprende una sintaxis sencilla y crea tus primeros proyectos.',javascriptTitle:'JavaScript',javascriptDescription:'Dale vida a tus páginas con lógica, eventos y programación web.',csharpTitle:'C#',csharpDescription:'Domina la base de C# y el ecosistema moderno de .NET'},
    course:{label:'CURSO',actions:'Funciones',actionBasic:'Ejecutar función básica',actionBasicDesc:'Acción simple de práctica.',actionAdvanced:'Explicación avanzada',actionAdvancedDesc:'Obtén una explicación más detallada.',actionExercise:'Generar ejercicio',actionExerciseDesc:'Crea un ejercicio personalizado.',actionComplex:'Análisis complejo',actionComplexDesc:'Solicita una revisión técnica avanzada.',actionPremium:'Función premium',actionPremiumDesc:'Herramienta avanzada para usuarios premium.',use:'Usar tokens',balance:'SALDO',insufficientTitle:'No tienes suficientes tokens',close:'Cerrar',upgradeCopyBronze:'Actualiza a Plata y obtén más tokens y beneficios.',upgradeCopySilver:'Actualiza a Oro para obtener el máximo acceso a MyCode.',upgradeCopyGold:'Ya tienes el plan más alto disponible.'},
    checkout:{eyebrow:'MEMBRESÍA',heading:'Activar tu plan',intro:'Esta pantalla está preparada para conectar un proveedor de pagos real.',selected:'Plan seleccionado',activate:'Continuar con el pago',secure:'Demo frontend. La confirmación de pago debe ocurrir en el backend.',successTitle:'¡Plan actualizado!',successText:'Tu nueva membresía ya está activa.',goDashboard:'Ir al dashboard'},
    ui:{themeLight:'Cambiar a modo claro',themeDark:'Cambiar a modo oscuro'}
  },
  en: {
    brand:'MyCode',
    nav:{courses:'Courses',plans:'Plans',dashboard:'Dashboard',login:'Log in',register:'Sign up',logout:'Log out',language:'Language',back:'← Back'},
    common:{browse:'Explore courses',open:'Open',select:'Select plan',update:'Upgrade plan',current:'Current plan',cancel:'Cancel',close:'Close',demo:'Frontend demo: do not use real data.',loading:'Loading…'},
    auth:{registerEyebrow:'CREATE ACCOUNT',registerTitle:'Start with MyCode',registerIntro:'Create your account and automatically receive the Bronze plan with 50 tokens.',username:'Username',email:'Email',password:'Password',confirmPassword:'Confirm password',birthDate:'Birth date',userType:'User type',student:'Student',general:'General user',create:'Create account',already:'Already have an account?',loginEyebrow:'MYCODE',loginTitle:'Log in',loginIntro:'Access your dashboard, courses and tokens.',identifier:'Username or email',submit:'Log in',noAccount:'No account?',invalidEmail:'Enter a valid email address.',required:'This field is required.',usernameMin:'Use between 3 and 30 characters.',passwordMin:'Password must be at least 8 characters and include uppercase, lowercase and a number.',passwordMismatch:'Passwords do not match.',duplicate:'This email is already registered.',invalidCredentials:'Invalid username or password.',unauthorized:'Unauthorized session.',forbidden:'You are not allowed to perform this action.',created:'Account created successfully.',loginSuccess:'Logged in successfully.',logoutSuccess:'Logged out.',showPassword:'Show password',hidePassword:'Hide password'},
    plans:{eyebrow:'MEMBERSHIPS',heading:'Choose your level',subheading:'More tokens, more tools and premium access.',invalidPlan:'Invalid plan',recommended:'RECOMMENDED',advanced:'FOR ADVANCED USERS',select:'Select plan',update:'Upgrade plan',changed:'Plan updated successfully.',bronzeDesc:'For getting started with learning and practice.',silverDesc:'For users who want more tools and usage headroom.',goldDesc:'The complete MyCode experience for advanced users.',bronzeBenefit1:'50 monthly tokens',bronzeBenefit2:'Basic content',bronzeBenefit3:'Essential features',silverBenefit1:'120 monthly tokens',silverBenefit2:'Expanded content',silverBenefit3:'More MyCode features',silverBenefit4:'Standard support',goldBenefit1:'350 monthly tokens',goldBenefit2:'All premium features',goldBenefit3:'Priority AI-based features',goldBenefit4:'Advanced programming tools',goldBenefit5:'Higher usage limits',goldBenefit6:'Early access to new features',goldBenefit7:'Priority support and exclusive benefits'},
    tokens:{required:'Required',available:'Available',consumed:'Usage completed.',lowTitle:'Your tokens are running low.',lowText:'Consider reviewing your plan.',criticalTitle:'You have very few tokens left.',criticalText:'Some features may become unavailable.',emptyTitle:'You have used all available tokens.',emptyText:'Upgrade your plan to continue using MyCode premium features.',viewPlans:'View plans',insufficient:'You do not have enough tokens for this feature.'},
    dashboard:{eyebrow:'DASHBOARD',hello:'Hello,',intro:'Manage your plan, tokens and activity in one place.',wallet:'WALLET',tokensTitle:'Available tokens',available:'Available',used:'Used',renewal:'Renewal',days:'days',currentPlan:'Current plan',history:'Token history',date:'Date',action:'Action',tokens:'Tokens',emptyHistory:'No activity yet.',explore:'Explore courses'},
    home:{eyebrow:'LEARN · BUILD · CODE',title:'Your code. Your next level.',intro:'A learning platform powered by memberships and consumable tokens.',catalog:'CATALOG',heading:'Languages to build with',subheading:'Access depends on your plan. Some features consume tokens.',memberships:'MEMBERSHIPS',membershipHeading:'Choose the level that fits you',membershipSubheading:'More tokens, more tools and premium access.',searchPlaceholder:'Search courses or content: variables, loops, Python…',searchLabel:'Search content',noResults:'No results found.',results:'Results'},
    courses:{cppTitle:'C++',cppDescription:'Fundamentals, logic, data structures and object-oriented programming.',javaTitle:'Java',javaDescription:'Build robust applications with classes, objects and good practices.',pythonTitle:'Python',pythonDescription:'Learn a simple syntax and build your first projects.',javascriptTitle:'JavaScript',javascriptDescription:'Bring your pages to life with logic, events and web programming.',csharpTitle:'C#',csharpDescription:'Master the basics of C# and the modern .NET ecosystem.'},
    course:{label:'COURSE',actions:'Features',actionBasic:'Run basic function',actionBasicDesc:'Simple practice action.',actionAdvanced:'Advanced explanation',actionAdvancedDesc:'Get a more detailed explanation.',actionExercise:'Generate exercise',actionExerciseDesc:'Create a custom exercise.',actionComplex:'Complex analysis',actionComplexDesc:'Request an advanced technical review.',actionPremium:'Premium feature',actionPremiumDesc:'Advanced tool for premium users.',use:'Use tokens',balance:'BALANCE',insufficientTitle:'Not enough tokens',close:'Close',upgradeCopyBronze:'Upgrade to Silver for more tokens and benefits.',upgradeCopySilver:'Upgrade to Gold for maximum MyCode access.',upgradeCopyGold:'You already have the highest plan.'},
    checkout:{eyebrow:'MEMBERSHIP',heading:'Activate your plan',intro:'This screen is ready to connect to a real payment provider.',selected:'Selected plan',activate:'Continue to payment',secure:'Frontend demo. Payment confirmation must occur on the backend.',successTitle:'Plan updated!',successText:'Your new membership is now active.',goDashboard:'Go to dashboard'},
    ui:{themeLight:'Switch to light mode',themeDark:'Switch to dark mode'}
  }
};

function getByPath(source, path) {
  return path.split('.').reduce((value, key) => value?.[key], source);
}

export function createI18n({ storage = globalThis.localStorage } = {}) {
  let language = storage?.getItem(CONFIG.storageKeys.language) || CONFIG.defaultLanguage;
  if (!translations[language]) language = CONFIG.defaultLanguage;

  const current = () => language;
  const set = (next) => {
    if (!translations[next]) return false;
    language = next;
    storage?.setItem(CONFIG.storageKeys.language, language);
    return true;
  };
  const get = (key) => getByPath(translations[language], key) ?? key;
  const has = (key) => getByPath(translations[language], key) !== undefined;

  return Object.freeze({ current, set, get, has, languages: () => Object.freeze(Object.keys(translations)) });
}

export { translations };
